apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-hub
resources:
  - rollout.yaml
  - service-stable.yaml
  - service-canary.yaml
  - httproute.yaml
images:
  - name: us-east1-docker.pkg.dev/project-385a0cab-c44a-4b07-926/devops-hub/frontend
    newTag: b5798a8
